### ISSUE TITLE
Use krb5_verify_user instead of krb5_get_init_creds_password

### ISSUE THREAD

**Issue by simmel** [simmel/rabbitmq-auth-backend-kerberos#3]
Use the more secure `krb5_verify_user` which uses a keytab to verify the KDC instead of `krb5_get_init_creds_password` which just trusts UDP and DNS that the KDC in use is the correct KDC.

Thanks to @eest for reporting it IRL = )

**Comment by alexsdutton** [comment]
I was just going to say that :-). http://web.mit.edu/kerberos/krb5-devel/doc/appdev/init_creds.html looks handy in explaining how to use `krb5_verify_init_creds`.

**Comment by simmel** [comment]
Ah yes, it seems like `krb5_verify_user` is Heimdal specific and that
using `krb5_verify_init_creds` will work for both Heimdal and and MIT.

Sadly we don't use RabbitMQ anymore and I would have to setup a dev
environment to test this. If I do the commit are you willing to test it
@alexsdutton?

If it works I can do a new release after.

**Comment by alexsdutton** [comment]
I'm not using this, and doubt I/we would be anytime soon (sorry!). I was wondering about GSSAPI/Kerberos support, which is how I came across your project.

I was playing with creating a web service to issue credentials based on how the client authenticates with that web service, that are then checked by RabbitMQ with the http auth backend. That way we can do crazy stuff with OAuth2, GSSAPI, etc.

**Comment by alexsdutton** [comment]
Your commit looks very plausible though, if that's any help.

**Comment by simmel** [comment]
On Thu, 2015-06-25 at 04:14:21 -0700, Alexander Dutton wrote:
> I'm not using this, and doubt I/we would be anytime soon (sorry!).

np = )

> I was wondering about GSSAPI/Kerberos support, which is how I came across your project.

Ah, I see! GSSAPI is sadly not plausible since you'd have to add GSSAPI
support to every AMQP client lib you are going to use. GSSAPI would be
awesome to have though = D

> I was playing with creating a web service to issue credentials based on how the client authenticates with that web service, that are then checked by RabbitMQ with the http auth backend. That way we can do crazy stuff with OAuth2, GSSAPI, etc.

Cool! GLHF!

And thank you for glancing over my commit!
